### ISSUE TITLE
It deleted entire /usr/bin directory

### ISSUE THREAD

**Issue by AnthonyWC** [rudolfb/sublime-text-3-install#1]
This script actually managed to deleted the entire /usr/bin/ directory.  Took me a good 2 hrs to recovery everything.  Teach me to never just glance at long script ever again before running..

**Comment by rudolfb** [comment]
Sorry about that. There are some heavy tools in the script

sudo rm -r "$CURRENT_SUBL_FOLDER"
sudo rm -r "$SUBL_TARGET_FOLDER"
sudo rm -r "$TEMPDIRECTORY"

I wonder what went wrong.

A while after I wrote this script packages became avaiable for installing Sublime Text, and then I started using tose instead of updating manually:

https://www.sublimetext.com/docs/3/linux_repositories.html

Haven't used this in years.
